"""Write .kuru/BOARD_HANDOFF.md for a new agent tab next to the board TUI."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from board.scheduler import RunResult

_HANDOFF_NAME = "BOARD_HANDOFF.md"

_ORIENT = """# Board handoff — for a new agent tab

_You are joining a Kurukuru workspace (possibly next to a board TUI). Reconstruct
state from files — do not assume chat history. This file is rewritten when a board
run finishes; `.kuru/progress.md` is the longer cross-session note._

## Orient (do this first)

1. Read **`.kuru/progress.md`** (current state, next action, landmines).
2. Run the engine (from the repo root):
   ```bash
   python3 "${KURU_PY:-$(cat .kuru/engine 2>/dev/null)}" doctor
   python3 "${KURU_PY:-$(cat .kuru/engine 2>/dev/null)}" ls
   python3 "${KURU_PY:-$(cat .kuru/engine 2>/dev/null)}" next
   ```
   If those fail, use the absolute path to `scripts/kuru.py` in the kurukuru plugin.
3. **Latest board run** (below) — `summary.json`, `config.json`, stage logs.
4. For a stuck/capped slice: `.kuru/slices/<id>/{contract.yml,build-log.md,verification.md}`
   and `.kuru/runs/<run_id>/<id>/*.log`.
5. Skim `.kuru/charter.md` (and `.kuru/profiles/` if present).

Then give a **5–8 line briefing**: board/ledger state, anything stuck, and **one**
recommended next action. Do not start a full board run or large refactor until
the user confirms.

## Rules (do not break)

- **Only `kuru.py` mutates** `ledger.json` / `gate-results.json` — never hand-edit.
- **Builder ≠ verifier**; a builder must not set `verified` / `reviewed`.
- **`verifying` means re-verify**, not rebuild.
- Board multi-slice ship uses **`--no-commit`**; end-of-run uses `kuru commit`.
- Same gate target → serialize; different targets may parallelize.

## Useful commands

```bash
python3 -m board plan --repo . --plugin-dir <plugin>
python3 -m board run -y --backend mock|claude|grok --repo . --plugin-dir <plugin>
python3 -m board status --repo .
# Optional TUI: <plugin>/scripts/board-tui.sh --repo .
```
"""


def handoff_path(repo: Path) -> Path:
    return Path(repo).resolve() / ".kuru" / _HANDOFF_NAME


def write_board_handoff(
    repo: Path,
    *,
    run_id: str,
    run_dir: Path,
    result: "RunResult",
    backend: str = "",
    review: bool | None = None,
) -> Path | None:
    """Rewrite BOARD_HANDOFF.md with the latest run. Best-effort; returns path or None."""
    path = handoff_path(repo)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        shipped = ", ".join(result.shipped) or "—"
        capped = ", ".join(result.capped) or "—"
        stuck_bits = []
        for s in result.stuck:
            if isinstance(s, dict):
                stuck_bits.append(f"{s.get('id', '?')} ({s.get('reason', '')})".rstrip())
            else:
                stuck_bits.append(str(s))
        stuck_s = "; ".join(stuck_bits) or "—"
        rev = (
            "on"
            if review is True
            else "off"
            if review is False
            else "?"
        )
        run_dir_rel = _rel(repo, run_dir)
        body = _ORIENT + f"""
## Latest board run

| | |
|--|--|
| **When** | {ts} |
| **Run id** | `{run_id}` |
| **Backend** | `{backend or "?"}` |
| **Review** | {rev} |
| **Shipped** | {shipped} |
| **Capped** | {capped} |
| **Stuck** | {stuck_s} |

### Paths (read these)

```text
{run_dir_rel}/summary.json     # outcomes
{run_dir_rel}/config.json      # how the run was launched
{run_dir_rel}/events.ndjson    # full event stream (TUI source)
{run_dir_rel}/<SL-xxxx>/*.log  # per-stage process logs
```

### Suggested next focus

"""
        if result.stuck:
            first = result.stuck[0]
            sid = first.get("id") if isinstance(first, dict) else str(first)
            body += (
                f"- Investigate **{sid}** (stuck). Read its stage logs under "
                f"`{run_dir_rel}/{sid}/` and the slice contract.\n"
            )
        elif result.capped:
            body += (
                f"- **{result.capped[0]}** hit the try budget. Read verify/build logs "
                f"and decide whether to re-run with a higher `--max-tries` or fix the contract.\n"
            )
        elif result.shipped:
            body += (
                "- Board cleared the actionable set for this run. "
                "Run `kuru next` / `kuru ls` for anything left (draft, blocked, new work).\n"
            )
        else:
            body += "- No slices shipped. Check preconditions and `kuru ls`.\n"

        body += (
            "\n---\n"
            f"_Generated by `board run` ({run_id}). "
            f"Also see `.kuru/progress.md` for the cross-session handoff._\n"
        )
        path.write_text(body, encoding="utf-8")
        return path
    except OSError:
        return None


def _rel(repo: Path, path: Path) -> str:
    try:
        return str(Path(path).resolve().relative_to(Path(repo).resolve()))
    except ValueError:
        return str(path)
